# Site settings
title: Helio Hackweek 2020
email: TBD@umd.edu
description: Workshop on Machine Learning in Heliophysics <br>
             University of Maryland <br>
             June 8-12, 2020 <br>
             Application Deadline March 31, 2020 <br> 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/heliohackWeek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://heliohackweek.slack.com
twitter_url:
email_url: TBD@umd.edu

# Build settings
markdown: kramdown

