# Site settings
title: Helio Hackweek 2020 (HW20)
email: TBD@umd.edu
description: Virtual Workshop on Machine Learning in Heliophysics, August 20-28, 2020 <br>
             *Congratulations to all of the Planners, Project Mentors, and Project Teams who coded with us!*<br>
          
 
            
            
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/heliohackWeek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: 
twitter_url:
email_url: 

# Build settings
markdown: kramdown

